default: &default
  adapter: postgresql
  host: <%= ENV['DBHOST'] %>
  database: <%= ENV['DBNAME'] %>
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASS'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
